package mod.wurmunlimited.treasury;

public enum TransactionType {
    COIN_AWARD,
    ECONOMIC_ADVISOR,
    PLAYER_PAYMENT_QUESTION,
    VILLAGE_EXPANSION,
    PARSE_EXPANSION,
    GUARD_RENTAL,
    DELETE_TRADER,
    NEW_SHOP,
    INTRA_SERVER_SET_PLAYER_MONEY,
    TRADING_WINDOW,
    DISCARD_SELL_ITEM,
    CREATURE_REMOVE_RANDOM
}
